// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Score struct {
	ID         int32              `json:"id"`
	PlayerName string             `json:"player_name"`
	WordID     int32              `json:"word_id"`
	Attempts   int32              `json:"attempts"`
	Solved     bool               `json:"solved"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Word struct {
	ID   int32       `json:"id"`
	Word string      `json:"word"`
	Date pgtype.Date `json:"date"`
}
