// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScore = `-- name: CreateScore :one
INSERT INTO scores (player_name, word_id, attempts, solved)
VALUES ($1, $2, $3, $4) RETURNING id, player_name, word_id, attempts, solved, created_at
`

type CreateScoreParams struct {
	PlayerName string `json:"player_name"`
	WordID     int32  `json:"word_id"`
	Attempts   int32  `json:"attempts"`
	Solved     bool   `json:"solved"`
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (Score, error) {
	row := q.db.QueryRow(ctx, createScore,
		arg.PlayerName,
		arg.WordID,
		arg.Attempts,
		arg.Solved,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.PlayerName,
		&i.WordID,
		&i.Attempts,
		&i.Solved,
		&i.CreatedAt,
	)
	return i, err
}

const createWord = `-- name: CreateWord :one
INSERT INTO words (word, date) VALUES ($1, $2) RETURNING id, word, date
`

type CreateWordParams struct {
	Word string      `json:"word"`
	Date pgtype.Date `json:"date"`
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Word, error) {
	row := q.db.QueryRow(ctx, createWord, arg.Word, arg.Date)
	var i Word
	err := row.Scan(&i.ID, &i.Word, &i.Date)
	return i, err
}

const getScoresByPlayer = `-- name: GetScoresByPlayer :many
SELECT s.id, s.player_name, s.word_id, s.attempts, s.solved, s.created_at, w.word, w.date
FROM scores s
JOIN words w ON s.word_id = w.id
WHERE s.player_name = $1
ORDER BY w.date DESC
`

type GetScoresByPlayerRow struct {
	ID         int32              `json:"id"`
	PlayerName string             `json:"player_name"`
	WordID     int32              `json:"word_id"`
	Attempts   int32              `json:"attempts"`
	Solved     bool               `json:"solved"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Word       string             `json:"word"`
	Date       pgtype.Date        `json:"date"`
}

func (q *Queries) GetScoresByPlayer(ctx context.Context, playerName string) ([]GetScoresByPlayerRow, error) {
	rows, err := q.db.Query(ctx, getScoresByPlayer, playerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScoresByPlayerRow
	for rows.Next() {
		var i GetScoresByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.WordID,
			&i.Attempts,
			&i.Solved,
			&i.CreatedAt,
			&i.Word,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoresByWord = `-- name: GetScoresByWord :many
SELECT id, player_name, word_id, attempts, solved, created_at FROM scores WHERE word_id = $1 ORDER BY attempts ASC
`

func (q *Queries) GetScoresByWord(ctx context.Context, wordID int32) ([]Score, error) {
	rows, err := q.db.Query(ctx, getScoresByWord, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.WordID,
			&i.Attempts,
			&i.Solved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayWord = `-- name: GetTodayWord :one
SELECT id, word, date FROM words WHERE date = CURRENT_DATE
`

func (q *Queries) GetTodayWord(ctx context.Context) (Word, error) {
	row := q.db.QueryRow(ctx, getTodayWord)
	var i Word
	err := row.Scan(&i.ID, &i.Word, &i.Date)
	return i, err
}

const getWordByDate = `-- name: GetWordByDate :one
SELECT id, word, date FROM words WHERE date = $1
`

func (q *Queries) GetWordByDate(ctx context.Context, date pgtype.Date) (Word, error) {
	row := q.db.QueryRow(ctx, getWordByDate, date)
	var i Word
	err := row.Scan(&i.ID, &i.Word, &i.Date)
	return i, err
}

const listWords = `-- name: ListWords :many
SELECT id, word, date FROM words ORDER BY date DESC
`

func (q *Queries) ListWords(ctx context.Context) ([]Word, error) {
	rows, err := q.db.Query(ctx, listWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(&i.ID, &i.Word, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
